# Generated by Django 6.0.1 on 2026-01-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la marque')),
                ('country', models.CharField(max_length=50, verbose_name="Pays d'origine")),
                ('founded_year', models.IntegerField(verbose_name='Année de création')),
            ],
        ),
        migrations.CreateModel(
            name='Trend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom de la tendance')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du vêtement')),
                ('sku', models.CharField(max_length=20, unique=True, verbose_name='Référence SKU')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('description', models.TextField(verbose_name='Description')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Stock')),
                ('release_date', models.DateField(verbose_name='Date de sortie')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, verbose_name='URL Image')),
                ('is_sustainable', models.BooleanField(default=False, verbose_name='Éco-responsable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='catalogue.designer')),
                ('trends', models.ManyToManyField(related_name='garments', to='catalogue.trend')),
            ],
        ),
    ]
